#!/bin/bash

echo "=== HuggingFace Spaces 部署脚本 ==="
echo ""
echo "请按照以下步骤操作："
echo ""
echo "1. 访问 https://huggingface.co/new-space"
echo "   - Owner: Quinnnnnne"
echo "   - Space name: soulmatch-agent"
echo "   - SDK: Docker"
echo "   - License: MIT"
echo ""
echo "2. 创建Space后，在本地执行："
echo ""
echo "   # 获取HuggingFace token"
echo "   # 访问 https://huggingface.co/settings/tokens"
echo "   # 创建一个write权限的token"
echo ""
echo "   # 配置git credential"
echo "   git remote set-url hf https://YOUR_USERNAME:YOUR_TOKEN@huggingface.co/spaces/Quinnnnnne/soulmatch-agent"
echo ""
echo "   # 推送代码"
echo "   git push hf main"
echo ""
echo "3. 在Space设置中配置环境变量："
echo "   Settings → Variables and secrets"
echo "   - OPENAI_API_KEY=你的密钥"
echo "   - GEMINI_API_KEY=你的密钥"
echo "   - DEEPSEEK_API_KEY=你的密钥"
echo ""
echo "4. 等待构建完成（约5-10分钟）"
echo ""
echo "5. 访问你的Space："
echo "   https://huggingface.co/spaces/Quinnnnnne/soulmatch-agent"
echo ""
echo "=== 当前项目状态 ==="
git log --oneline -5
echo ""
echo "所有部署文件已准备就绪！"
